### ISSUE TITLE
Slow performance of tree grid for large json.

### ISSUE THREAD

**Issue by IamTejasPatel** [khan4019/tree-grid-directive#75] opened 2015-12-23 09:20 UTC
I am facing considerable lag in select/deselect , collapse/expend tree etc. I have attached json file , can you provide me work around. Also I have attached  my tree grid screenshot.

[data.zip](https://github.com/khan4019/tree-grid-directive/files/70576/data.zip)

**Comment by sumedhkalaskar** [comment] 2015-12-24 06:24
facing the same issue for 5000+ array size. it stop expanding tree and throw script error.

**Comment by TrueDub** [comment] 2016-07-05 15:21
This would be caused by the sheer size of your arrays - Angular's two-way binding is slow with datasets of that size. I'm not sure a workaround is possible.

**Comment by TrueDub** [comment] 2016-07-11 09:50
closing due to lack of further update

**Closed by TrueDub** 2016-07-11 09:50 UTC
