### ISSUE TITLE
Tree-Grid is taking the expanding property into another column.

### ISSUE THREAD

**Issue by amathad** [khan4019/tree-grid-directive#29] opened 2015-01-30 00:31 UTC
Tree-Grid is taking the expanding property into another column. Shouldn't it be combined with initial/first column and should keep aligning with it as we go on expanding ? I'm using the same treegrid.css styles and tree-grid definition. What might be wrong ?

Is it some thing related to style ?

![image](https://cloud.githubusercontent.com/assets/6423649/5969106/a609b99a-a7dc-11e4-89bd-289b6c477a58.png)

**Comment by diosney** [comment] 2015-02-10 23:29
I think this is related to https://github.com/graywolf336/tree-grid-directive/commit/17c25162d34bfc8bce3084fccdfd888bad5e4b84#commitcomment-9686221

I will try to fix it by tomorrow since I needed too :)

**Comment by diosney** [comment] 2015-02-11 17:23
Now the issue is fixed, until the PR is accepted, you can use the repo at https://github.com/diosney/tree-grid-directive

**Comment by diosney** [comment] 2015-02-12 14:39
@khan4019 You can closed this issue too, its already merged and included in the README.

**Closed** 2015-02-12 15:59 UTC
